-- create users
DECLARE @ApplicationId    INT;
DECLARE @ApplicationName  NVARCHAR(256);
DECLARE @AdminUserName    NVARCHAR(256);
DECLARE @AdminUserEmail   NVARCHAR(256);
DECLARE @NormalUserName   NVARCHAR(256);
DECLARE @NormalUserEmail  NVARCHAR(256);
DECLARE @Password         NVARCHAR(256);


SET     @ApplicationName = 'wm';
SET     @AdminUserName = 'admin';
SET     @AdminUserEmail = 'admin@wm.com';
SET     @NormalUserName = 'jim';
SET     @NormalUserEmail = 'jim@wm.com';
SET     @Password = '123';



DECLARE @NewId        UNIQUEIDENTIFIER;
DECLARE @ReturnValue  INT;
DECLARE @Message      NVARCHAR(MAX);

SET   @Message = 'find default application "' +  @ApplicationName + '"';
PRINT @Message;
SELECT  @ApplicationId = ApplicationId
FROM    wm_Applications
WHERE   LoweredApplicationName = LOWER(@ApplicationName)

IF ( @ApplicationId IS NULL )
BEGIN
  SET   @Message = 'application "' +  @ApplicationName + '" not found, create';
  PRINT @Message;
  EXEC @ApplicationId = wm_Applications_Insert @ApplicationName, 'Autogenerated via test setup script';
END

SET @NewId = NEWID();
SET   @Message = 'create admin user "' +  @AdminUserName + '"';
PRINT @Message;

DECLARE @DateCreatedUtc DATETIME;
DECLARE @UserId         INT;

EXEC @ReturnValue = wm_Users_Insert
  @ApplicationId
, @AdminUserName -- @UserName = 'admin'
, @AdminUserEmail -- @Email = 'admin@workmate.com'
, @Password
, NULL -- @PasswordSalt = 'rbwHN7mDIoVza7HF5kehoA=='
, 0 -- @PasswordFormat = 0
, 1 -- @Status = 1
, '''SystemAdministrator'',''Registered''' -- @RoleNames = 
, 1 -- @ProfileImageId
, @NewId -- @UniqueId =
, 1 -- @UserNameDisplayMode
, 'GMT Standard Time' -- @TimeZoneInfoId =
, @AdminUserName -- @FirstName =
, @AdminUserName -- @LastName =
, @UserId OUT -- NULL -- @UserId =
, @DateCreatedUtc OUT -- @DateCreatedUtc =

IF ( @ReturnValue <= 0 )
BEGIN
  SET   @Message = 'admin user "' +  @AdminUserName + '" not created. ErrorCode: ' + CAST(@ReturnValue AS NVARCHAR(MAX));
  PRINT @Message;
  
  SELECT * FROM wm_SqlErrorLog
END