IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[cms_FileTag]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[cms_FileTag](
	[FileId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_cms_FileTag] PRIMARY KEY CLUSTERED 
(
	[FileId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)
END
GO